### PR TITLE
Change to Open Tech Calendar

### PR DESCRIPTION
**Pull request by jarofgreen**
I can update the text on the page from the admin interface, but here is a new JS file for this.

I also added HTML escaping which I guess we should have had before? Not sure if this is a complete way of doing it.

### CODE REVIEW

**Comment by latentflip** [comment]
I'm assuming this is dead now that we've done the jekyll handover?

**Comment by jarofgreen** [comment]
This has been done for the main event page. If anyone wants to copy the JS to TechMeetup static site and improve it tho that's cool.

If wanted this could also be done for per event pages, pulling events for that group only and listing them so the next dates and speaker details could be easily seen.

**Comment by latentflip** [comment]
So what's the deal exactly? If we include this snippet we can update details on OTC and have them pulled into the static site?

**Comment by jarofgreen** [comment]
Yup. You can include various filters, like a certain group only to.

**Comment by latentflip** [comment]
<3 okay, can you chuck a note in the redesign thing about it.

**Comment by jarofgreen** [comment]
Have done this on individual event pages in https://github.com/daleharvey/techmeetup/pull/13

**Pull request closed without merging**
